# Pandas Data Structure 数据结构

### 1. 一维数组 Series


In [2]:
import pandas as pd
list = [11,22,33,44,55,66,77,88,99]

- 通过list构建Series -- series = pd.Series(list)
- Index is auto-created 

In [7]:
series = pd.Series(list)
series

0    11
1    22
2    33
3    44
4    55
5    66
6    77
7    88
8    99
dtype: int64

In [6]:
ser_obj = pd.Series(range(10, 20))
print(type(ser_obj))

<class 'pandas.core.series.Series'>


- 获取索引和数据

In [9]:
# 获取数据
print(ser_obj.values)

# 获取索引
print(ser_obj.index)

[10 11 12 13 14 15 16 17 18 19]
RangeIndex(start=0, stop=10, step=1)


In [10]:
# 预览数据
print(ser_obj.head(3))

0    10
1    11
2    12
dtype: int64


In [12]:
#通过索引获取数据 -- through Index not Key
print(ser_obj[0])
print(ser_obj[8])

10
18


In [14]:
# 索引与数据的对应关系仍保持在数组运算的结果中

print(ser_obj[ser_obj > 15])

# starts from 6 other than 0

6    16
7    17
8    18
9    19
dtype: int64


In [15]:
# 通过dict构建Series

year_data = {2001: 17.8, 2002: 20.1, 2003: 16.5}
ser_obj2 = pd.Series(year_data)
print(ser_obj2.head())
print(ser_obj2.index)

2001    17.8
2002    20.1
2003    16.5
dtype: float64
Int64Index([2001, 2002, 2003], dtype='int64')


In [17]:
# name属性

ser_obj2.name = 'temp'
ser_obj2.index.name = 'year'
print(ser_obj2.head())

year
2001    17.8
2002    20.1
2003    16.5
Name: temp, dtype: float64


### 2. 多维数组 DataFrame
#### 通过ndarray 构建DataFrame

In [18]:
import numpy as np

# 通过ndarray构建DataFrame

array = np.random.randn(5,4)
print(array)

df_obj = pd.DataFrame(array)
print(df_obj.head())

[[ 0.27860763  0.63832532  0.87175361  1.47336268]
 [-0.21032713 -1.50721275  0.40318211 -1.86635528]
 [-1.92527969 -0.17191099  1.46547995 -0.10708743]
 [ 0.76387433 -0.14896082 -2.68583588 -0.03820051]
 [-0.61688567 -0.04359984  0.31010367  0.15018619]]
          0         1         2         3
0  0.278608  0.638325  0.871754  1.473363
1 -0.210327 -1.507213  0.403182 -1.866355
2 -1.925280 -0.171911  1.465480 -0.107087
3  0.763874 -0.148961 -2.685836 -0.038201
4 -0.616886 -0.043600  0.310104  0.150186


#### 通过dict构建DataFrame

In [22]:

dict_data = {'A': 1., 
             'B': pd.Timestamp('20171217'),
             'C': pd.Series(1, index=(range(4)),dtype='float32'),
             'D': np.array([3] * 4,dtype='int32'),
             'E' : pd.Categorical(["Python","Java","C++","C#"])
            }
#print dict_data
df_obj2 = pd.DataFrame(dict_data)
print(df_obj2.head())

     A          B    C  D       E
0  1.0 2017-12-17  1.0  3  Python
1  1.0 2017-12-17  1.0  3    Java
2  1.0 2017-12-17  1.0  3     C++
3  1.0 2017-12-17  1.0  3      C#


In [24]:
# 通过列索引获取列数据

print(df_obj2['A'])

0    1.0
1    1.0
2    1.0
3    1.0
Name: A, dtype: float64


In [25]:
# 增加列

df_obj2['G'] = df_obj2['D'] + 4
print(df_obj2.head())

     A          B    C  D       E  G
0  1.0 2017-12-17  1.0  3  Python  7
1  1.0 2017-12-17  1.0  3    Java  7
2  1.0 2017-12-17  1.0  3     C++  7
3  1.0 2017-12-17  1.0  3      C#  7


In [26]:
# 删除列

del(df_obj2['G'] )
print(df_obj2.head())

     A          B    C  D       E
0  1.0 2017-12-17  1.0  3  Python
1  1.0 2017-12-17  1.0  3    Java
2  1.0 2017-12-17  1.0  3     C++
3  1.0 2017-12-17  1.0  3      C#


### 3. 索引对象 Index
- Series和DataFrame中的索引都是Index对象
- Immutable 不可变 （保证了数据的安全）
- 常见的Index类型： Index, Int64Index, MultiIndex, DatetimeIndex)

In [27]:
print(type(ser_obj.index))
print(type(df_obj2.index))

print(df_obj2.index)

<class 'pandas.core.indexes.range.RangeIndex'>
<class 'pandas.core.indexes.range.RangeIndex'>
RangeIndex(start=0, stop=4, step=1)


In [ ]:
# 索引对象不可变

df_obj2.index[0] = 2

# -> report error: Index does not support mutable operations