# From scikit-learn to Know Machine Learning

### Feature engineering and feature types
- numerical: apply()
- Ordinal: A, B , C --> 0, 1, 2 // low, median, high -> -1 , 0 , 1
- categical: car, house, busines --> OneHotEncoder()

### Feature is the alias of factor or variable in other domian.
- Like Multivariates Analysis

### Supervised Learning v.s. Unsupervised Learning
- Supervised learning: with 'labels'.
 * Classfication -- sample labels is discrete
 * Regression: sample labels include one or more continous variables


- Unsupervised learning: without 'lables'


### Train set / Validation set / Test set
- Training set: train the model
- Validation set: tuning the model and select the best model
- Test set: test the model

In [2]:
from sklearn import datasets
iris = datasets.load_iris()
digits = datasets.load_digits()

In [9]:
# iris
print(iris.data.shape)
print(iris.data[:10])

# one row as one sample -- 150
# one colomn as a feature -- 4


(150, 4)
[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]]


In [7]:
print(iris.target_names) 
print(iris.target) # labels

['setosa' 'versicolor' 'virginica']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [12]:
# digits

print(digits.data.shape) # 64 -- pixel 8*8
print(digits.data[:5])


(1797, 64)
[[  0.   0.   5.  13.   9.   1.   0.   0.   0.   0.  13.  15.  10.  15.
    5.   0.   0.   3.  15.   2.   0.  11.   8.   0.   0.   4.  12.   0.
    0.   8.   8.   0.   0.   5.   8.   0.   0.   9.   8.   0.   0.   4.
   11.   0.   1.  12.   7.   0.   0.   2.  14.   5.  10.  12.   0.   0.
    0.   0.   6.  13.  10.   0.   0.   0.]
 [  0.   0.   0.  12.  13.   5.   0.   0.   0.   0.   0.  11.  16.   9.
    0.   0.   0.   0.   3.  15.  16.   6.   0.   0.   0.   7.  15.  16.
   16.   2.   0.   0.   0.   0.   1.  16.  16.   3.   0.   0.   0.   0.
    1.  16.  16.   6.   0.   0.   0.   0.   1.  16.  16.   6.   0.   0.
    0.   0.   0.  11.  16.  10.   0.   0.]
 [  0.   0.   0.   4.  15.  12.   0.   0.   0.   0.   3.  16.  15.  14.
    0.   0.   0.   0.   8.  13.   8.  16.   0.   0.   0.   0.   1.   6.
   15.  11.   0.   0.   0.   1.   8.  13.  15.   1.   0.   0.   0.   9.
   16.  16.   5.   0.   0.   0.   0.   3.  13.  16.  16.  11.   5.   0.
    0.   0.   0.   3.  11.  16.   9.   

In [13]:
print(digits.target_names)
print(digits.target)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 ..., 8 9 8]


### Traning the Model using Training Set

In [20]:
from sklearn import svm

# use SVM
# SVM is one of the best algorithms in image process before deep learning
svm_classifier = svm.SVC(gamma=0.001, C=100.)
# svm_classifier = svm.SVC(gamma=100., C=1.)

# Split train set and test set by hands
n_test = 100 # no.test set=100
train_X = digits.data[:-n_test, :]
train_y = digits.target[:-n_test]

test_X = digits.data[-n_test:, :]
y_true = digits.target[-n_test:]

# train the model: fit()
svm_classifier.fit(train_X, train_y)

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

### Test the Model in Test set 

In [25]:
y_pred = svm_classifier.predict(test_X)

In [23]:

from sklearn.metrics import accuracy_score

print('pred labels: ', y_pred)
print('true labels:', y_true)

print('accuracy: ', accuracy_score(y_true, y_pred))

pred labels:  [0 9 5 5 6 5 0 9 8 9 8 4 1 7 7 3 5 1 0 0 2 2 7 8 2 0 1 2 6 3 8 7 5 3 4 6 6
 6 4 9 1 5 0 9 5 2 8 2 0 0 1 7 6 3 2 1 7 4 6 3 1 3 9 1 7 6 8 4 3 1 4 0 5 3
 6 9 6 1 7 5 4 4 7 2 8 2 2 5 7 9 5 4 8 8 4 9 0 8 9 8]
true labels: [0 9 5 5 6 5 0 9 8 9 8 4 1 7 7 3 5 1 0 0 2 2 7 8 2 0 1 2 6 3 3 7 3 3 4 6 6
 6 4 9 1 5 0 9 5 2 8 2 0 0 1 7 6 3 2 1 7 4 6 3 1 3 9 1 7 6 8 4 3 1 4 0 5 3
 6 9 6 1 7 5 4 4 7 2 8 2 2 5 7 9 5 4 8 8 4 9 0 8 9 8]
accuracy:  0.98


### Save the Model

In [26]:
import pickle

with open('svm_model.pkl', 'wb') as f:
    pickle.dump(svm_classifier, f)

In [28]:
import numpy as np

# reload the model and reuse to predict
with open('svm_model.pkl', 'rb') as f:
    model = pickle.load(f)

random_samples_index = np.random.randint(0, 1796, 5)
random_samples = digits.data[random_samples_index, :]
random_targets = digits.target[random_samples_index]

random_predict = model.predict(random_samples)

print(random_predict)
print(random_targets)
print('accuracy: ', accuracy_score(random_targets, random_predict))

[9 6 6 5 2]
[9 6 6 5 2]
accuracy:  1.0
